name: test pip install

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 1,3,5"

jobs:
  build:

    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Check if cmake is installed
      run: |
        cmake --version
  
    - name: Install kima
      run: |
        #pip install --extra-index-url https://test.pypi.org/simple  kima
        python -m pip install kima

    - name: Test import
      run: |
        python -c "import kima"
        python -c "from kima import RVData, RVmodel, GPmodel"

    - name: Run 51Peg example
      run : |
        python -c "from kima import examples; examples._51Peg(run=True, load=True, steps=100)"
