name: test pip install

on:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * 1,3,5"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        # this should be taken care of by pip, but fails for test-pypi
        pip install scikit-build-core nanobind

    - name: Install kima
      run: |
        pip install -i https://test.pypi.org/simple/ kima
        #pip install kima

    - name: Test import
      run: |
        python -c "import kima"
